SELECT A.customer_id, A.customer_name
FROM CUSTOMERS A
JOIN ORDERS B ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.customer_id, A.customer_name
HAVING SUM(CASE WHEN B.PRODUCT_NAME = 'A' THEN 1 ELSE 0 END) > 0
   AND SUM(CASE WHEN B.PRODUCT_NAME = 'B' THEN 1 ELSE 0 END) > 0
   AND SUM(CASE WHEN B.PRODUCT_NAME = 'C' THEN 1 ELSE 0 END) = 0
ORDER BY A.customer_name;